# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 816206145fdd8ca48efdc97ff891d0ddf9bddae511c0f4180acbd88f00fd4a0a632c15873a52d37742fa95219f1dc460c4a579ef62e6f66a1dd353c9bfa62ccb

test:
  secret_key_base: a547965ac77590dcf02aee69e81ec8c59a280b0dae5db0cea9b437db23e9dbd404ac94121f98b52313a5462b38ccb67a03692112704ab971b6b4f0db6aa6e3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
